title: Introduction to Blockchain Research Skills
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/intro-blockchain-research/\">View in GitHub</a>"
